var annotated =
[
    [ "AnisotropicFilter", "class_anisotropic_filter.html", "class_anisotropic_filter" ],
    [ "BinaryComponentExtractor", "class_binary_component_extractor.html", "class_binary_component_extractor" ],
    [ "ComponentExtractor", "class_component_extractor.html", "class_component_extractor" ],
    [ "ConnectedComponent", "class_connected_component.html", "class_connected_component" ],
    [ "Contour", "class_contour.html", "class_contour" ],
    [ "DImage", "class_d_image.html", "class_d_image" ],
    [ "Feature", "class_feature.html", "class_feature" ],
    [ "FeatureExtractor", "class_feature_extractor.html", "class_feature_extractor" ],
    [ "GaborBlobExtractor", "class_gabor_blob_extractor.html", "class_gabor_blob_extractor" ],
    [ "GaborBlobFeature", "class_gabor_blob_feature.html", "class_gabor_blob_feature" ],
    [ "GlobalBinarizer", "class_global_binarizer.html", "class_global_binarizer" ],
    [ "Histogram", "class_histogram.html", "class_histogram" ],
    [ "ImageBinarizer", "class_image_binarizer.html", "class_image_binarizer" ],
    [ "ImageConverter", "class_image_converter.html", "class_image_converter" ],
    [ "ImageEnhancer", "class_image_enhancer.html", "class_image_enhancer" ],
    [ "ImageFilter", "class_image_filter.html", "class_image_filter" ],
    [ "ImageOperator", "class_image_operator.html", "class_image_operator" ],
    [ "ImageProjector", "class_image_projector.html", "class_image_projector" ],
    [ "IntFeature", "class_int_feature.html", "class_int_feature" ],
    [ "ItayBinarizer", "class_itay_binarizer.html", "class_itay_binarizer" ],
    [ "Metric", "class_metric.html", "class_metric" ],
    [ "MetricDTW", "class_metric_d_t_w.html", "class_metric_d_t_w" ],
    [ "OtsuBinarizer", "class_otsu_binarizer.html", "class_otsu_binarizer" ],
    [ "OtsulBinarizer", "class_otsul_binarizer.html", "class_otsul_binarizer" ],
    [ "PageImage", "class_page_image.html", "class_page_image" ],
    [ "ProfileSeamTextLineExtractor", "class_profile_seam_text_line_extractor.html", "class_profile_seam_text_line_extractor" ],
    [ "ProjectionProfile", "class_projection_profile.html", "class_projection_profile" ],
    [ "RafiTextLineExtractor", "class_rafi_text_line_extractor.html", "class_rafi_text_line_extractor" ],
    [ "ScalarFeature", "class_scalar_feature.html", "class_scalar_feature" ],
    [ "TextLineExtractor", "class_text_line_extractor.html", "class_text_line_extractor" ],
    [ "ThresholdBinarizer", "class_threshold_binarizer.html", "class_threshold_binarizer" ]
];